// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-edit-summary'
  | 'pref-help'
  | 'pref-title'
  | 'pref-wikibase-url'
  | 'pref-wikibase-url-help'
  | 'prefs-title';
